--
-- Critical Hit Manager
-- Added by Dancher
--
-- See also:
--	actor_critical_hit.script
--  ui_actor_critical_hit.script
--  sound_actor_critical_hit.script
--

local hit_chance_by_rank = {
	["novice"] 			= 6,
	["trainee"] 		= 8,
	["experienced"]		= 10,
	["professional"]    = 12,
	["veteran"]         = 14,
	["expert"]          = 16,
	["master"]          = 18,
	["legend"]          = 20
}

local hit_multiplier = 0.25

local crit_enabled_option_name = "can_stalker_crit_hit"
local crit_cam_vfx_option_name = "show_crit_hit_cam_vfx"
local crit_mark_option_name = "show_crit_hit_mark"
local crit_sound_option_name = "play_crit_hit_sound"

local function get_hit_chance(who)
	local rank = ranks.get_obj_rank_name(who)
	local chance = hit_chance_by_rank[rank] or 0
	return chance
end

local function calculate_hit_modificator(max, value)
	return utils.lerp(0, max, value)
end

local function calculate_hit_damage(base_damage, who)
	local modificator = 0
	if (IsActor(who)) then
		modificator = modificator + calculate_hit_modificator(0.1, 1 - who.bleeding)
		modificator = modificator + calculate_hit_modificator(0.1, 1 - who.radiation)
		modificator = modificator + calculate_hit_modificator(0.1, who.health)
		modificator = modificator + calculate_hit_modificator(0.1, who.power)
		modificator = modificator + calculate_hit_modificator(0.1, who.psy_health)
		modificator = modificator + calculate_hit_modificator(0.1, who.satiety)
	else
		modificator = modificator + calculate_hit_modificator(0.3, 1 - who.bleeding)
		modificator = modificator + calculate_hit_modificator(0.3, who.health)
	end
	
	local hit_damage = base_damage * hit_multiplier * (1 + modificator)
	return hit_damage
end

local function try_hit(victim, damage, who)
	local can_hit = get_chance() <= get_hit_chance(who)
	
	if (can_hit) then
		local hit_damage = calculate_hit_damage(damage, who)
		victim.health = -(hit_damage / 100)
		-- printf(string.format(">>> Dancher: critical_hit_manager.script -> Orignal damage is %0.2f. Additional crit damage is %0.2f.", damage, hit_damage))
	end
	
	return can_hit
end

local function npc_or_monster_on_hit_callback(victim, damage, _, who, _)
	if (victim:alive() and IsStalker(who) and
		axr_main_options.get_check_option(crit_enabled_option_name)) 
	then
		local has_hit = try_hit(victim, damage, who)
		
		if (has_hit and IsActor(who)) then
			if (axr_main_options.get_check_option(crit_mark_option_name)) then
				ui_actor_critical_hit.show_mark()
			end
			
			if (axr_main_options.get_check_option(crit_sound_option_name)) then
				sound_actor_critical_hit.play_sound()
			end
		end
	end
end

local function actor_on_hit_callback(victim, damage, _, who, _)
	if (victim:alive() and IsStalkerOnly(who) and 
		axr_main_options.get_check_option(crit_enabled_option_name)) 
	then
		local has_hit = try_hit(victim, damage, who)

		if (has_hit) then
			if (axr_main_options.get_check_option(crit_cam_vfx_option_name)) then
				ui_actor_critical_hit.show_cam_effector()
			end
			
			if (axr_main_options.get_check_option(crit_sound_option_name)) then
				sound_actor_critical_hit.play_sound()
			end
		end
	end
end

function on_game_start()
	RegisterScriptCallback("npc_on_hit_callback", npc_or_monster_on_hit_callback)
	RegisterScriptCallback("monster_on_hit_callback", npc_or_monster_on_hit_callback)
	RegisterScriptCallback("actor_on_hit_callback", actor_on_hit_callback)
end
