--
--	Script functions for cooking recipes dialog (dialogs_cooking_recipes.xml)
--	Author: Dancher
--

function not_has_recipes(actor, npc)
	local has_recipes = cooking_recipes_manager.has_actor_recipes_from(npc)
	return has_recipes == false
end

function give_recipes(npc, actor)
	local recipe_sections = cooking_recipes_manager.give_actor_recipes_from(npc)
	news_cooking_recipes.give_news(recipe_sections)
end
