--
-- Leave the Zone
-- Author: Dancher
--

local function make_finish_save()
	local character_name = alife():actor():character_name()
	local level_name = game.translate_string(level.name())
	local finish_text = game.translate_string("ui_st_leave_zone_finish_save")
	
	local save_name = string.format("%s %s %s", character_name, level_name, finish_text)
	local save_command = string.format("save %s", save_name)
	get_console():execute(save_command)
end

local function finish_game()
	xr_effects.game_credits()
	
	local function postpone_for_next_frame()
		make_finish_save()
		xr_effects.game_disconnect()
	end
	
	SkipFrame(postpone_for_next_frame)
end

local function physic_object_on_use_callback(obj,who) 
	if (obj:section() == "leave_zone_object") then
		show_ui_dialog()
	end
end

function show_ui_dialog()
	local function on_yes_button_clicked()
		finish_game()
	end
	ui_dialog_confirm.dialog("st_freeplay_text_yes_no", on_yes_button_clicked)
end

function on_game_start()
	-- For versions below 1.5.2
	RegisterScriptCallback("physic_object_on_use_callback",physic_object_on_use_callback)
end
