--
-- Возвращение озвучки смерти НПС by av661194
-- Оптимизация/рефакторинг by Dancher
--

local head_bone_name = "bip01_head"
local far_distance_sqr = 900

local snd_obj
local last_snd_tbl

local function get_death_sound_tbl(community)
	if (community == "stalker") then
		return {
			"characters_voice\\human_01\\stalker\\fight\\death\\death_1",
			"characters_voice\\human_01\\stalker\\fight\\death\\death_2",
			"characters_voice\\human_01\\stalker\\fight\\death\\death_3",
			"characters_voice\\human_01\\stalker\\fight\\death\\death_4",
			"characters_voice\\human_01\\stalker\\fight\\death\\death_5",
			"characters_voice\\human_01\\stalker\\fight\\death\\death_6",
			"characters_voice\\human_01\\stalker\\fight\\death\\death_7",
			"characters_voice\\human_01\\stalker\\fight\\death\\death_8",
		
			"characters_voice\\human_02\\stalker\\fight\\death\\death_1",
			"characters_voice\\human_02\\stalker\\fight\\death\\death_2",
			"characters_voice\\human_02\\stalker\\fight\\death\\death_3",
			"characters_voice\\human_02\\stalker\\fight\\death\\death_4",
			"characters_voice\\human_02\\stalker\\fight\\death\\death_5",
			"characters_voice\\human_02\\stalker\\fight\\death\\death_6",
			"characters_voice\\human_02\\stalker\\fight\\death\\death_7",
			"characters_voice\\human_02\\stalker\\fight\\death\\death_8",
			"characters_voice\\human_02\\stalker\\fight\\death\\death_9",
		
			"characters_voice\\human_03\\stalker\\fight\\death\\death_1",
			"characters_voice\\human_03\\stalker\\fight\\death\\death_2",
			"characters_voice\\human_03\\stalker\\fight\\death\\death_3",
			"characters_voice\\human_03\\stalker\\fight\\death\\death_4",
			"characters_voice\\human_03\\stalker\\fight\\death\\death_5",
			"characters_voice\\human_03\\stalker\\fight\\death\\death_6",
			"characters_voice\\human_03\\stalker\\fight\\death\\death_7"
		}
	end
	
	if (community == "dolg") then
		return {
			"characters_voice\\human_01\\dolg\\fight\\death\\death_1",
			"characters_voice\\human_01\\dolg\\fight\\death\\death_2",
			"characters_voice\\human_01\\dolg\\fight\\death\\death_3",
		    
			"characters_voice\\human_02\\dolg\\fight\\death\\death_1",
			"characters_voice\\human_02\\dolg\\fight\\death\\death_2",
			"characters_voice\\human_02\\dolg\\fight\\death\\death_3",
		    
			"characters_voice\\human_03\\dolg\\fight\\death\\death_1",
			"characters_voice\\human_03\\dolg\\fight\\death\\death_2",
			"characters_voice\\human_03\\dolg\\fight\\death\\death_3"
		}
	end
	
	if (community == "freedom") then
		return {
			"characters_voice\\human_01\\freedom\\fight\\death\\death_1",
			"characters_voice\\human_01\\freedom\\fight\\death\\death_2",
			"characters_voice\\human_01\\freedom\\fight\\death\\death_3",
			"characters_voice\\human_01\\freedom\\fight\\death\\death_4",
			"characters_voice\\human_01\\freedom\\fight\\death\\death_5",
			"characters_voice\\human_01\\freedom\\fight\\death\\death_6",
			"characters_voice\\human_01\\freedom\\fight\\death\\death_7",
			"characters_voice\\human_01\\freedom\\fight\\death\\death_8",
			
			"characters_voice\\human_02\\freedom\\fight\\death\\death_1",
			"characters_voice\\human_02\\freedom\\fight\\death\\death_2",
			"characters_voice\\human_02\\freedom\\fight\\death\\death_3",
			"characters_voice\\human_02\\freedom\\fight\\death\\death_4",
			"characters_voice\\human_02\\freedom\\fight\\death\\death_5",
			"characters_voice\\human_02\\freedom\\fight\\death\\death_6",
			"characters_voice\\human_02\\freedom\\fight\\death\\death_7",
			"characters_voice\\human_02\\freedom\\fight\\death\\death_8",
			
			"characters_voice\\human_03\\freedom\\fight\\death\\death_1",
			"characters_voice\\human_03\\freedom\\fight\\death\\death_2",
			"characters_voice\\human_03\\freedom\\fight\\death\\death_3",
			"characters_voice\\human_03\\freedom\\fight\\death\\death_4",
			"characters_voice\\human_03\\freedom\\fight\\death\\death_5",
			"characters_voice\\human_03\\freedom\\fight\\death\\death_6",
			"characters_voice\\human_03\\freedom\\fight\\death\\death_7",
			"characters_voice\\human_03\\freedom\\fight\\death\\death_8"
		}
	end
	
	if (community == "killer") then
		return {
			"characters_voice\\human_01\\killer\\fight\\death\\death_1",
			"characters_voice\\human_01\\killer\\fight\\death\\death_2",
			"characters_voice\\human_01\\killer\\fight\\death\\death_3",
			"characters_voice\\human_01\\killer\\fight\\death\\death_4",
			"characters_voice\\human_01\\killer\\fight\\death\\death_5",
			"characters_voice\\human_01\\killer\\fight\\death\\death_6",
			"characters_voice\\human_01\\killer\\fight\\death\\death_7",
		    
			"characters_voice\\human_02\\killer\\fight\\death\\death_1",
			"characters_voice\\human_02\\killer\\fight\\death\\death_2",
			"characters_voice\\human_02\\killer\\fight\\death\\death_3",
			"characters_voice\\human_02\\killer\\fight\\death\\death_4",
			"characters_voice\\human_02\\killer\\fight\\death\\death_5",
			"characters_voice\\human_02\\killer\\fight\\death\\death_6",
			"characters_voice\\human_02\\killer\\fight\\death\\death_7",
		    
			"characters_voice\\human_03\\killer\\fight\\death\\death_1",
			"characters_voice\\human_03\\killer\\fight\\death\\death_2",
			"characters_voice\\human_03\\killer\\fight\\death\\death_3",
			"characters_voice\\human_03\\killer\\fight\\death\\death_4",
			"characters_voice\\human_03\\killer\\fight\\death\\death_5",
			"characters_voice\\human_03\\killer\\fight\\death\\death_6",
			"characters_voice\\human_03\\killer\\fight\\death\\death_7"
		}
	end
	
	if (community == "csky") then
		return {
			"characters_voice\\human_01\\csky\\fight\\death\\death_1",
			"characters_voice\\human_01\\csky\\fight\\death\\death_2",
			"characters_voice\\human_01\\csky\\fight\\death\\death_3",
			"characters_voice\\human_01\\csky\\fight\\death\\death_4",
			"characters_voice\\human_01\\csky\\fight\\death\\death_5",
			"characters_voice\\human_01\\csky\\fight\\death\\death_6",
			"characters_voice\\human_01\\csky\\fight\\death\\death_7",
		    
			"characters_voice\\human_02\\csky\\fight\\death\\death_1",
			"characters_voice\\human_02\\csky\\fight\\death\\death_2",
			"characters_voice\\human_02\\csky\\fight\\death\\death_3",
			"characters_voice\\human_02\\csky\\fight\\death\\death_4",
			"characters_voice\\human_02\\csky\\fight\\death\\death_5",
			"characters_voice\\human_02\\csky\\fight\\death\\death_6",
			"characters_voice\\human_02\\csky\\fight\\death\\death_7",
		    
			"characters_voice\\human_03\\csky\\fight\\death\\death_1",
			"characters_voice\\human_03\\csky\\fight\\death\\death_2",
			"characters_voice\\human_03\\csky\\fight\\death\\death_3",
			"characters_voice\\human_03\\csky\\fight\\death\\death_4",
			"characters_voice\\human_03\\csky\\fight\\death\\death_5",
			"characters_voice\\human_03\\csky\\fight\\death\\death_6",
			"characters_voice\\human_03\\csky\\fight\\death\\death_7"
		}
	end
	
	if (community == "monolith") then
		return {
			"characters_voice\\human_01\\monolith\\fight\\death\\death_1",
			"characters_voice\\human_01\\monolith\\fight\\death\\death_2",
			"characters_voice\\human_01\\monolith\\fight\\death\\death_3",
			"characters_voice\\human_01\\monolith\\fight\\death\\death_4",
			"characters_voice\\human_01\\monolith\\fight\\death\\death_5",
			"characters_voice\\human_01\\monolith\\fight\\death\\death_6",
			"characters_voice\\human_01\\monolith\\fight\\death\\death_7",
			"characters_voice\\human_01\\monolith\\fight\\death\\death_8",
		    
			"characters_voice\\human_02\\monolith\\fight\\death\\death_1",
			"characters_voice\\human_02\\monolith\\fight\\death\\death_2",
			"characters_voice\\human_02\\monolith\\fight\\death\\death_3",
			"characters_voice\\human_02\\monolith\\fight\\death\\death_4",
			"characters_voice\\human_02\\monolith\\fight\\death\\death_5",
			"characters_voice\\human_02\\monolith\\fight\\death\\death_6",
			"characters_voice\\human_02\\monolith\\fight\\death\\death_7",
			"characters_voice\\human_02\\monolith\\fight\\death\\death_8",
		    
			"characters_voice\\human_03\\monolith\\fight\\death\\death_1",
			"characters_voice\\human_03\\monolith\\fight\\death\\death_2",
			"characters_voice\\human_03\\monolith\\fight\\death\\death_3",
			"characters_voice\\human_03\\monolith\\fight\\death\\death_4",
			"characters_voice\\human_03\\monolith\\fight\\death\\death_5",
			"characters_voice\\human_03\\monolith\\fight\\death\\death_6",
			"characters_voice\\human_03\\monolith\\fight\\death\\death_7",
			"characters_voice\\human_03\\monolith\\fight\\death\\death_8"
		}
	end
	
	if (community == "army") then
		return {
			"characters_voice\\human_01\\military\\fight\\death\\death_1",
			"characters_voice\\human_01\\military\\fight\\death\\death_2",
			"characters_voice\\human_01\\military\\fight\\death\\death_3",
			"characters_voice\\human_01\\military\\fight\\death\\death_4",
			"characters_voice\\human_01\\military\\fight\\death\\death_5",
		    
			"characters_voice\\human_02\\military\\fight\\death\\death_1",
			"characters_voice\\human_02\\military\\fight\\death\\death_2",
			"characters_voice\\human_02\\military\\fight\\death\\death_3",
			"characters_voice\\human_02\\military\\fight\\death\\death_4",
			"characters_voice\\human_02\\military\\fight\\death\\death_5",
		    
			"characters_voice\\human_03\\military\\fight\\death\\death_1",
			"characters_voice\\human_03\\military\\fight\\death\\death_2",
			"characters_voice\\human_03\\military\\fight\\death\\death_3",
			"characters_voice\\human_03\\military\\fight\\death\\death_4",
			"characters_voice\\human_03\\military\\fight\\death\\death_5"
		}
	end
	
	if (community == "ecolog") then
		return {
			"characters_voice\\human_01\\ecolog\\fight\\death\\death_1",
			"characters_voice\\human_01\\ecolog\\fight\\death\\death_2",
			"characters_voice\\human_01\\ecolog\\fight\\death\\death_3",
			"characters_voice\\human_01\\ecolog\\fight\\death\\death_4",
			"characters_voice\\human_01\\ecolog\\fight\\death\\death_5",
			"characters_voice\\human_01\\ecolog\\fight\\death\\death_6",
			"characters_voice\\human_01\\ecolog\\fight\\death\\death_7",
			"characters_voice\\human_01\\ecolog\\fight\\death\\death_8",
			"characters_voice\\human_01\\ecolog\\fight\\death\\death_9",
		    
			"characters_voice\\human_02\\ecolog\\fight\\death\\death_1",
			"characters_voice\\human_02\\ecolog\\fight\\death\\death_2",
			"characters_voice\\human_02\\ecolog\\fight\\death\\death_3",
			"characters_voice\\human_02\\ecolog\\fight\\death\\death_4",
			"characters_voice\\human_02\\ecolog\\fight\\death\\death_5",
			"characters_voice\\human_02\\ecolog\\fight\\death\\death_6",
			"characters_voice\\human_02\\ecolog\\fight\\death\\death_7",
			"characters_voice\\human_02\\ecolog\\fight\\death\\death_8",
			"characters_voice\\human_02\\ecolog\\fight\\death\\death_9",
			
			"characters_voice\\human_03\\ecolog\\fight\\death\\death_1",
			"characters_voice\\human_03\\ecolog\\fight\\death\\death_2",
			"characters_voice\\human_03\\ecolog\\fight\\death\\death_3",
			"characters_voice\\human_03\\ecolog\\fight\\death\\death_4",
			"characters_voice\\human_03\\ecolog\\fight\\death\\death_5",
			"characters_voice\\human_03\\ecolog\\fight\\death\\death_6",
			"characters_voice\\human_03\\ecolog\\fight\\death\\death_7",
			"characters_voice\\human_03\\ecolog\\fight\\death\\death_8",
			"characters_voice\\human_03\\ecolog\\fight\\death\\death_9"
		}
	end
	
	if (community == "bandit") then
		return {
			"characters_voice\\human_01\\bandit\\fight\\death\\death_1",
			"characters_voice\\human_01\\bandit\\fight\\death\\death_2",
			"characters_voice\\human_01\\bandit\\fight\\death\\death_3",
			"characters_voice\\human_01\\bandit\\fight\\death\\death_4",
			"characters_voice\\human_01\\bandit\\fight\\death\\death_5",
			"characters_voice\\human_01\\bandit\\fight\\death\\death_6",
			"characters_voice\\human_01\\bandit\\fight\\death\\death_7",
		    
			"characters_voice\\human_02\\bandit\\fight\\death\\death_1",
			"characters_voice\\human_02\\bandit\\fight\\death\\death_2",
			"characters_voice\\human_02\\bandit\\fight\\death\\death_3",
			"characters_voice\\human_02\\bandit\\fight\\death\\death_4",
			"characters_voice\\human_02\\bandit\\fight\\death\\death_5",
			"characters_voice\\human_02\\bandit\\fight\\death\\death_6",
			"characters_voice\\human_02\\bandit\\fight\\death\\death_7",
			"characters_voice\\human_02\\bandit\\fight\\death\\death_8",
		    
			"characters_voice\\human_03\\bandit\\fight\\death\\death_1",
			"characters_voice\\human_03\\bandit\\fight\\death\\death_2",
			"characters_voice\\human_03\\bandit\\fight\\death\\death_3",
			"characters_voice\\human_03\\bandit\\fight\\death\\death_4",
			"characters_voice\\human_03\\bandit\\fight\\death\\death_5",
			"characters_voice\\human_03\\bandit\\fight\\death\\death_6",
			"characters_voice\\human_03\\bandit\\fight\\death\\death_7"
		}
	end
	
	if (community == "zombied") then
		return {
			"characters_voice\\human_01\\zombied\\fight\\death\\death_1",
			"characters_voice\\human_01\\zombied\\fight\\death\\death_2",
			"characters_voice\\human_01\\zombied\\fight\\death\\death_3",
			"characters_voice\\human_01\\zombied\\fight\\death\\death_4",
			"characters_voice\\human_01\\zombied\\fight\\death\\death_5",
			"characters_voice\\human_01\\zombied\\fight\\death\\death_6",
		    
			"characters_voice\\human_02\\zombied\\fight\\death\\death_1",
			"characters_voice\\human_02\\zombied\\fight\\death\\death_2",
			"characters_voice\\human_02\\zombied\\fight\\death\\death_3",
			"characters_voice\\human_02\\zombied\\fight\\death\\death_4",
			"characters_voice\\human_02\\zombied\\fight\\death\\death_5",
			"characters_voice\\human_02\\zombied\\fight\\death\\death_6",
		    
			"characters_voice\\human_03\\zombied\\fight\\death\\death_1",
			"characters_voice\\human_03\\zombied\\fight\\death\\death_2",
			"characters_voice\\human_03\\zombied\\fight\\death\\death_3",
			"characters_voice\\human_03\\zombied\\fight\\death\\death_4",
			"characters_voice\\human_03\\zombied\\fight\\death\\death_5",
			"characters_voice\\human_03\\zombied\\fight\\death\\death_6"
		}
	end
	
	local default_tbl = {
		"characters_voice\\human_01\\stalker\\fight\\death\\death_4",
		"characters_voice\\human_01\\stalker\\fight\\death\\death_5",
		"characters_voice\\human_01\\stalker\\fight\\death\\death_6",
		"characters_voice\\human_01\\stalker\\fight\\death\\death_7",
		"characters_voice\\human_01\\stalker\\fight\\death\\death_8",
		
		"characters_voice\\human_02\\killer\\fight\\death\\death_1",
		"characters_voice\\human_02\\killer\\fight\\death\\death_2",
		"characters_voice\\human_02\\killer\\fight\\death\\death_3",
		"characters_voice\\human_02\\killer\\fight\\death\\death_4",
		"characters_voice\\human_02\\killer\\fight\\death\\death_5",
		
		"characters_voice\\human_03\\military\\fight\\death\\death_1",
		"characters_voice\\human_03\\military\\fight\\death\\death_2",
		"characters_voice\\human_03\\military\\fight\\death\\death_3",
		"characters_voice\\human_03\\military\\fight\\death\\death_4"
	}
	
	if (community == "arena_enemy") then
		return default_tbl
	end
	
	return default_tbl
end

local function npc_on_death_callback(victim)
	local community = victim:character_community()
	local snd_tbl = (last_snd_tbl and last_snd_tbl[community]) or nil
	
	if (snd_tbl == nil) then
		snd_tbl = get_death_sound_tbl(community)
		last_snd_tbl = { [community] = snd_tbl }
	end
	
	local snd_path = snd_tbl[math.random(#snd_tbl)]
	snd_obj = sound_object(snd_path)
	
	if (snd_obj == nil) then
		return
	end
	
	local actor = db.actor
	local actor_pos = actor:position()
	local npc_pos = victim:position()
	local is_npc_far = actor_pos:distance_to_sqr(npc_pos) > far_distance_sqr
	
	if (is_npc_far) then
		snd_obj:play_at_pos(victim, alun_utils.safe_bone_pos(victim, head_bone_name))
	else
		snd_obj:play_at_pos(actor, vector():set(npc_pos.x - actor_pos.x, npc_pos.y - actor_pos.y, npc_pos.z - actor_pos.z), 0, sound_object.s2d)
	end
end

function on_game_start()
	RegisterScriptCallback("npc_on_death_callback", npc_on_death_callback)
end