--
-- Manager for PDA Upgrade
-- Added by Dancher
--

-- No off upgrade

function has_no_off_upgrade()
	return db.actor:has_info("no_off_pda_upgrade")
end

function give_no_off_upgrade()
	db.actor:give_info_portion("no_off_pda_upgrade")
end

-- Squads on map upgrade

function has_squads_on_map_upgrade()
	return db.actor:has_info("squads_on_map_pda_upgrade")
end

function give_squads_on_map_upgrade()
	db.actor:give_info_portion("squads_on_map_pda_upgrade")
end
