--
-- Sound for Critical Hit
-- Added by Dancher
--

local volume = 0.5
local sound_delta_time = 25
local sound_paths = {
	"actor\\hurt2",
	"actor\\hurt3",
	"actor\\hurt5",
	"actor\\hurt6",
	"actor\\hurt7"
}

local sound_time = nil

local function get_sound()
	local sound_path = sound_paths[math.random(#sound_paths)]
	local sound = xr_sound.get_safe_sound_object(sound_path)
	return sound
end

function play_sound()
	local time_global = time_global()
	if (sound_time and sound_time > time_global) then
		return
	end
	local sound = get_sound()
	sound:play_no_feedback(db.actor, sound_object.s2d, 0, VEC_ZERO, volume)
	sound_time = time_global + sound_delta_time
end
