--------------------------------------------
-- Unload All Weapons (CoC 1.4.22 / 1.5 R6)
-- script version 8
-- author: sLoPpYdOtBiGhOlE
-- adapted: Dancher
--------------------------------------------
local bgl,bsi,bsc
local unload_sound_path = "weapons\\gen_empty"

function unload_weapons()
	local inventory = ActorMenu.get_actor_menu()
	
	if not (inventory and inventory:IsShown()) then 
		return 
	end
	
	local ta, tb, ts = {}, {}, {}
	local i, k, v
	ts["wpn_knife"] = true
	ts["wpn_binoc"] = true
	for i=1,12 do
		k = db.actor:item_in_slot(i)
		if (k) then
			ts[k:id()] = true
		end
	end
	
	if (string.find(GAME_VERSION,"1.4")) then
		local function itr(npc,itm)
			if (not ts[itm:id()] and not ts[itm:section()]) then
				unload_weapon(itm)
			end
		end
		db.actor:iterate_inventory(itr,db.actor)
	end
	
	xr_sound.play_sound_by_path(unload_sound_path,true)
end

function unload_weapon(itm)
	local i, k, v
	if (IsWeapon(itm)) then
		i = itm:get_ammo_in_magazine()
		if (i > 0) then
			k = itm and alife():object(itm:id())
			v = k and stpk_utils.get_weapon_data(k)
			if (v) then
				k = system_ini():r_string_ex(itm:section(),"ammo_class",STR_EMPTY)
				if (k and k ~= STR_EMPTY) then
					k = alun_utils.str_explode(k,STR_COMMA)
					if (k) then
						k = k[v.ammo_type + 1]
						if (k and k ~= STR_EMPTY) then
							itm:unload_magazine()
							create_ammo(k,db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id(),i)
						end
					end
				end
			end
		end
	end
end